version: '3'
services:

  mongo:
      image: mongo
      restart: always
      ports:
       - "27017:27017"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    container_name: find-a-bank-server
    volumes:
       - ./server:/usr/src/app/api
       - /usr/src/app/api/node_modules
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    container_name: find-a-bank-client
    stdin_open: true
    volumes:
       - ./client:/usr/src/app/client-app
       - /usr/src/app/client-app/node_modules
    depends_on:
      - server